# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html
[tool.black]
line-length = 120

# https://beta.ruff.rs/docs/settings/
[tool.ruff]
line-length = 120
# https://beta.ruff.rs/docs/rules/
select = ["E", "W", "F", "D", "UP", "PL"]
ignore = ["F401", "F841", "D10", "PLR091", "PLR2004"]
# Exclude a variety of commonly ignored directories.
respect-gitignore = true
ignore-init-module-imports = true

[tool.ruff.lint.pydocstyle]
convention = "google"

# FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
[tool.pyright]
exclude = [
    "data",
    "logs",
]
typeCheckingMode = "off"